---
title: Super korte samenvatting van The Fountainhead
author: Wim van der Ham
date: '2018-06-15'
slug: the-fountainhead
categories:
  - samenvatting
tags:
  - Ayn Rand
---

Moch je van plan zijn `The Fountainhead` van *Ayn Rand* te gaan lezen, doe het niet. Lees deze super korte samenvatting en bespaar uren van je leven.

# Howard Roark

De hoofdpersoon van het boek is *Howard Roark*. Hij heeft de volgende kenmerken:

* Is een extreem goede architect. Zijn gebouwen worden unaniem fantastisch gevonden door mensen die zich niet laten beïnvloeden door bijvoorbeeld de media.
* Maakt alleen een gebouw als hij volledige vrijheid krijgt.

Verschillende keren in het verhaal wordt hem gevraagd of hij wat concessies wil doen aan zijn werk, zijn antwoord is altijd nee. Als hij genoeg opdrachten heeft werkt hij als architect, zo niet dan doet hij simpel werk wat hij ook leuk vind.

# Peter Keating

* Is een middelmatige architect
* Geeft uitsluitend om de mening van andere mensen over hem (in het bijzonder zijn moeder).
* Vervult al zijn wensen door middel van het manipuleren van andere mensen en met een beetje hulp van *Howard Roark*. Het maakt hem echter niet gelukkig.

# Ellsworth Toohey

* Is een columnist bij de *Banner* en heeft veel invloed bij veel groepen.
* Wil macht over de wereld krijgen door iedereen afhankelijk te maken van wat andere mensen van hem of haar denken.
* Wil personen elimineren die nooit afhankelijk zullen zijn van iemand anders, zoals *Howard Roark*.

# Gail Wynand

* Miljonair en eigenaar van de *Banner*. Een krant die zijn lezers precies geeft wat ze willen (sensatie).
* Wil uitsluiten macht over andere mensen.
* Gebruikt deze macht om *Howard Roark* te verdedigen nadat ze vrienden zijn geworden. Hij slaagt daar niet in wat de ondergang van de *Banner* betekend.
* Denkt lange tijd dat hij net als *Howard Roark* compleet onafhankelijk van mensen is, totdat hij zich realiseert dat macht over iemand hebben je ook afhankelijk van die persoon maakt.

# Dominique Francon

Vrouw die verlieft wordt op *Howard Roark* nadat hij haar verkracht. Maar om zichzelf te straffen trouwt ze eerst nog met *Peter Keating* en *Gail Wynand*. Daarna trouwt ze dan toch met *Howard Roark* en ze leven nog lang en gelukkig.

# Mijn Mening

Wat het boek niet zo interessant maakt is dat *Howard Roark* niks te verliezen heeft. Hij heeft geen familie of vrienden, al zijn gebouwen zijn super goed, als hij niet werkt als architect dan werkt hij als iets anders wat hij eigenlijk ook wel prima vind. Is verlieft op *Dominique Francon* maar vind het niet echt erg als ze grote delen van de tijd met andere mannen getrouwd is. Als je niks te verliezen hebt in geen concessies doen erg makkelijk.

Een ander probleem is dat geven om andere mensen en geven om de mening van andere mensen over jou als hetzelfde wordt gezien. Beide worden altruïsme genoemd. Ik den dat je prima om andere mensen kan geven, zonder je al te veel aan te trekken van wat andere mensen van je vinden.

# Belangrijkste Pagina's

140, 142, 158, 260, 261, 267, 270, 283, 311, 307, 317, 321, 336, 337, 340, 366, 374, 400, 442, 475, 490, 513, 574, 576, 595, 633, 634, 664, 666, 667, 717
